channels:
- conda-forge
dependencies:
- python=3.10.9
- pip<=24.3.1
- pip:
  - mlflow==2.17.1
  - cloudpickle==2.0.0
  - lz4==3.1.3
  - numpy==1.24.4
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.0.2
  - scipy==1.10.1
name: mlflow-env
